INSERT INTO Landen (land) VALUES ('Andorra');
INSERT INTO Landen (land) VALUES ('United Arab Emirates');
INSERT INTO Landen (land) VALUES ('Afghanistan');
INSERT INTO Landen (land) VALUES ('Antigua and Barbuda');
INSERT INTO Landen (land) VALUES ('Anguilla');
INSERT INTO Landen (land) VALUES ('Albania');
INSERT INTO Landen (land) VALUES ('Armenia');
INSERT INTO Landen (land) VALUES ('Angola');
INSERT INTO Landen (land) VALUES ('Antarctica');
INSERT INTO Landen (land) VALUES ('Argentina');
INSERT INTO Landen (land) VALUES ('American Samoa');
INSERT INTO Landen (land) VALUES ('Austria');
INSERT INTO Landen (land) VALUES ('Australia');
INSERT INTO Landen (land) VALUES ('Aruba');
INSERT INTO Landen (land) VALUES ('Åland');
INSERT INTO Landen (land) VALUES ('Azerbaijan');
INSERT INTO Landen (land) VALUES ('Bosnia and Herzegovina');
INSERT INTO Landen (land) VALUES ('Barbados');
INSERT INTO Landen (land) VALUES ('Bangladesh');
INSERT INTO Landen (land) VALUES ('Belgium');
INSERT INTO Landen (land) VALUES ('Burkina Faso');
INSERT INTO Landen (land) VALUES ('Bulgaria');
INSERT INTO Landen (land) VALUES ('Bahrain');
INSERT INTO Landen (land) VALUES ('Burundi');
INSERT INTO Landen (land) VALUES ('Benin');
INSERT INTO Landen (land) VALUES ('Saint Barthélemy');
INSERT INTO Landen (land) VALUES ('Bermuda');
INSERT INTO Landen (land) VALUES ('Brunei');
INSERT INTO Landen (land) VALUES ('Bolivia');
INSERT INTO Landen (land) VALUES ('Bonaire');
INSERT INTO Landen (land) VALUES ('Brazil');
INSERT INTO Landen (land) VALUES ('Bahamas');
INSERT INTO Landen (land) VALUES ('Bhutan');
INSERT INTO Landen (land) VALUES ('Bouvet Island');
INSERT INTO Landen (land) VALUES ('Botswana');
INSERT INTO Landen (land) VALUES ('Belarus');
INSERT INTO Landen (land) VALUES ('Belize');
INSERT INTO Landen (land) VALUES ('Canada');
INSERT INTO Landen (land) VALUES ('Cocos [Keeling] Islands');
INSERT INTO Landen (land) VALUES ('Democratic Republic of the Congo');
INSERT INTO Landen (land) VALUES ('Central African Republic');
INSERT INTO Landen (land) VALUES ('Republic of the Congo');
INSERT INTO Landen (land) VALUES ('Switzerland');
INSERT INTO Landen (land) VALUES ('Ivory Coast');
INSERT INTO Landen (land) VALUES ('Cook Islands');
INSERT INTO Landen (land) VALUES ('Chile');
INSERT INTO Landen (land) VALUES ('Cameroon');
INSERT INTO Landen (land) VALUES ('China');
INSERT INTO Landen (land) VALUES ('Colombia');
INSERT INTO Landen (land) VALUES ('Costa Rica');
INSERT INTO Landen (land) VALUES ('Cuba');
INSERT INTO Landen (land) VALUES ('Cape Verde');
INSERT INTO Landen (land) VALUES ('Curacao');
INSERT INTO Landen (land) VALUES ('Christmas Island');
INSERT INTO Landen (land) VALUES ('Cyprus');
INSERT INTO Landen (land) VALUES ('Czech Republic');
INSERT INTO Landen (land) VALUES ('Germany');
INSERT INTO Landen (land) VALUES ('Djibouti');
INSERT INTO Landen (land) VALUES ('Denmark');
INSERT INTO Landen (land) VALUES ('Dominica');
INSERT INTO Landen (land) VALUES ('Dominican Republic');
INSERT INTO Landen (land) VALUES ('Algeria');
INSERT INTO Landen (land) VALUES ('Ecuador');
INSERT INTO Landen (land) VALUES ('Estonia');
INSERT INTO Landen (land) VALUES ('Egypt');
INSERT INTO Landen (land) VALUES ('Western Sahara');
INSERT INTO Landen (land) VALUES ('Eritrea');
INSERT INTO Landen (land) VALUES ('Spain');
INSERT INTO Landen (land) VALUES ('Ethiopia');
INSERT INTO Landen (land) VALUES ('Finland');
INSERT INTO Landen (land) VALUES ('Fiji');
INSERT INTO Landen (land) VALUES ('Falkland Islands');
INSERT INTO Landen (land) VALUES ('Micronesia');
INSERT INTO Landen (land) VALUES ('Faroe Islands');
INSERT INTO Landen (land) VALUES ('France');
INSERT INTO Landen (land) VALUES ('Gabon');
INSERT INTO Landen (land) VALUES ('United Kingdom');
INSERT INTO Landen (land) VALUES ('Grenada');
INSERT INTO Landen (land) VALUES ('Georgia');
INSERT INTO Landen (land) VALUES ('French Guiana');
INSERT INTO Landen (land) VALUES ('Guernsey');
INSERT INTO Landen (land) VALUES ('Ghana');
INSERT INTO Landen (land) VALUES ('Gibraltar');
INSERT INTO Landen (land) VALUES ('Greenland');
INSERT INTO Landen (land) VALUES ('Gambia');
INSERT INTO Landen (land) VALUES ('Guinea');
INSERT INTO Landen (land) VALUES ('Guadeloupe');
INSERT INTO Landen (land) VALUES ('Equatorial Guinea');
INSERT INTO Landen (land) VALUES ('Greece');
INSERT INTO Landen (land) VALUES ('South Georgia and the South Sandwich Islands');
INSERT INTO Landen (land) VALUES ('Guatemala');
INSERT INTO Landen (land) VALUES ('Guam');
INSERT INTO Landen (land) VALUES ('Guinea-Bissau');
INSERT INTO Landen (land) VALUES ('Guyana');
INSERT INTO Landen (land) VALUES ('Hong Kong');
INSERT INTO Landen (land) VALUES ('Heard Island and McDonald Islands');
INSERT INTO Landen (land) VALUES ('Honduras');
INSERT INTO Landen (land) VALUES ('Croatia');
INSERT INTO Landen (land) VALUES ('Haiti');
INSERT INTO Landen (land) VALUES ('Hungary');
INSERT INTO Landen (land) VALUES ('Indonesia');
INSERT INTO Landen (land) VALUES ('Ireland');
INSERT INTO Landen (land) VALUES ('Israel');
INSERT INTO Landen (land) VALUES ('Isle of Man');
INSERT INTO Landen (land) VALUES ('India');
INSERT INTO Landen (land) VALUES ('British Indian Ocean Territory');
INSERT INTO Landen (land) VALUES ('Iraq');
INSERT INTO Landen (land) VALUES ('Iran');
INSERT INTO Landen (land) VALUES ('Iceland');
INSERT INTO Landen (land) VALUES ('Italy');
INSERT INTO Landen (land) VALUES ('Jersey');
INSERT INTO Landen (land) VALUES ('Jamaica');
INSERT INTO Landen (land) VALUES ('Jordan');
INSERT INTO Landen (land) VALUES ('Japan');
INSERT INTO Landen (land) VALUES ('Kenya');
INSERT INTO Landen (land) VALUES ('Kyrgyzstan');
INSERT INTO Landen (land) VALUES ('Cambodia');
INSERT INTO Landen (land) VALUES ('Kiribati');
INSERT INTO Landen (land) VALUES ('Comoros');
INSERT INTO Landen (land) VALUES ('Saint Kitts and Nevis');
INSERT INTO Landen (land) VALUES ('North Korea');
INSERT INTO Landen (land) VALUES ('South Korea');
INSERT INTO Landen (land) VALUES ('Kuwait');
INSERT INTO Landen (land) VALUES ('Cayman Islands');
INSERT INTO Landen (land) VALUES ('Kazakhstan');
INSERT INTO Landen (land) VALUES ('Laos');
INSERT INTO Landen (land) VALUES ('Lebanon');
INSERT INTO Landen (land) VALUES ('Saint Lucia');
INSERT INTO Landen (land) VALUES ('Liechtenstein');
INSERT INTO Landen (land) VALUES ('Sri Lanka');
INSERT INTO Landen (land) VALUES ('Liberia');
INSERT INTO Landen (land) VALUES ('Lesotho');
INSERT INTO Landen (land) VALUES ('Lithuania');
INSERT INTO Landen (land) VALUES ('Luxembourg');
INSERT INTO Landen (land) VALUES ('Latvia');
INSERT INTO Landen (land) VALUES ('Libya');
INSERT INTO Landen (land) VALUES ('Morocco');
INSERT INTO Landen (land) VALUES ('Monaco');
INSERT INTO Landen (land) VALUES ('Moldova');
INSERT INTO Landen (land) VALUES ('Montenegro');
INSERT INTO Landen (land) VALUES ('Saint Martin');
INSERT INTO Landen (land) VALUES ('Madagascar');
INSERT INTO Landen (land) VALUES ('Marshall Islands');
INSERT INTO Landen (land) VALUES ('Macedonia');
INSERT INTO Landen (land) VALUES ('Mali');
INSERT INTO Landen (land) VALUES ('Myanmar [Burma]');
INSERT INTO Landen (land) VALUES ('Mongolia');
INSERT INTO Landen (land) VALUES ('Macao');
INSERT INTO Landen (land) VALUES ('Northern Mariana Islands');
INSERT INTO Landen (land) VALUES ('Martinique');
INSERT INTO Landen (land) VALUES ('Mauritania');
INSERT INTO Landen (land) VALUES ('Montserrat');
INSERT INTO Landen (land) VALUES ('Malta');
INSERT INTO Landen (land) VALUES ('Mauritius');
INSERT INTO Landen (land) VALUES ('Maldives');
INSERT INTO Landen (land) VALUES ('Malawi');
INSERT INTO Landen (land) VALUES ('Mexico');
INSERT INTO Landen (land) VALUES ('Malaysia');
INSERT INTO Landen (land) VALUES ('Mozambique');
INSERT INTO Landen (land) VALUES ('Namibia');
INSERT INTO Landen (land) VALUES ('New Caledonia');
INSERT INTO Landen (land) VALUES ('Niger');
INSERT INTO Landen (land) VALUES ('Norfolk Island');
INSERT INTO Landen (land) VALUES ('Nigeria');
INSERT INTO Landen (land) VALUES ('Nicaragua');
INSERT INTO Landen (land) VALUES ('Netherlands');
INSERT INTO Landen (land) VALUES ('Norway');
INSERT INTO Landen (land) VALUES ('Nepal');
INSERT INTO Landen (land) VALUES ('Nauru');
INSERT INTO Landen (land) VALUES ('Niue');
INSERT INTO Landen (land) VALUES ('New Zealand');
INSERT INTO Landen (land) VALUES ('Oman');
INSERT INTO Landen (land) VALUES ('Panama');
INSERT INTO Landen (land) VALUES ('Peru');
INSERT INTO Landen (land) VALUES ('French Polynesia');
INSERT INTO Landen (land) VALUES ('Papua New Guinea');
INSERT INTO Landen (land) VALUES ('Philippines');
INSERT INTO Landen (land) VALUES ('Pakistan');
INSERT INTO Landen (land) VALUES ('Poland');
INSERT INTO Landen (land) VALUES ('Saint Pierre and Miquelon');
INSERT INTO Landen (land) VALUES ('Pitcairn Islands');
INSERT INTO Landen (land) VALUES ('Puerto Rico');
INSERT INTO Landen (land) VALUES ('Palestine');
INSERT INTO Landen (land) VALUES ('Portugal');
INSERT INTO Landen (land) VALUES ('Palau');
INSERT INTO Landen (land) VALUES ('Paraguay');
INSERT INTO Landen (land) VALUES ('Qatar');
INSERT INTO Landen (land) VALUES ('Réunion');
INSERT INTO Landen (land) VALUES ('Romania');
INSERT INTO Landen (land) VALUES ('Serbia');
INSERT INTO Landen (land) VALUES ('Russia');
INSERT INTO Landen (land) VALUES ('Rwanda');
INSERT INTO Landen (land) VALUES ('Saudi Arabia');
INSERT INTO Landen (land) VALUES ('Solomon Islands');
INSERT INTO Landen (land) VALUES ('Seychelles');
INSERT INTO Landen (land) VALUES ('Sudan');
INSERT INTO Landen (land) VALUES ('Sweden');
INSERT INTO Landen (land) VALUES ('Singapore');
INSERT INTO Landen (land) VALUES ('Saint Helena');
INSERT INTO Landen (land) VALUES ('Slovenia');
INSERT INTO Landen (land) VALUES ('Svalbard and Jan Mayen');
INSERT INTO Landen (land) VALUES ('Slovakia');
INSERT INTO Landen (land) VALUES ('Sierra Leone');
INSERT INTO Landen (land) VALUES ('San Marino');
INSERT INTO Landen (land) VALUES ('Senegal');
INSERT INTO Landen (land) VALUES ('Somalia');
INSERT INTO Landen (land) VALUES ('Suriname');
INSERT INTO Landen (land) VALUES ('South Sudan');
INSERT INTO Landen (land) VALUES ('São Tomé and Príncipe');
INSERT INTO Landen (land) VALUES ('El Salvador');
INSERT INTO Landen (land) VALUES ('Sint Maarten');
INSERT INTO Landen (land) VALUES ('Syria');
INSERT INTO Landen (land) VALUES ('Swaziland');
INSERT INTO Landen (land) VALUES ('Turks and Caicos Islands');
INSERT INTO Landen (land) VALUES ('Chad');
INSERT INTO Landen (land) VALUES ('French Southern Territories');
INSERT INTO Landen (land) VALUES ('Togo');
INSERT INTO Landen (land) VALUES ('Thailand');
INSERT INTO Landen (land) VALUES ('Tajikistan');
INSERT INTO Landen (land) VALUES ('Tokelau');
INSERT INTO Landen (land) VALUES ('East Timor');
INSERT INTO Landen (land) VALUES ('Turkmenistan');
INSERT INTO Landen (land) VALUES ('Tunisia');
INSERT INTO Landen (land) VALUES ('Tonga');
INSERT INTO Landen (land) VALUES ('Turkey');
INSERT INTO Landen (land) VALUES ('Trinidad and Tobago');
INSERT INTO Landen (land) VALUES ('Tuvalu');
INSERT INTO Landen (land) VALUES ('Taiwan');
INSERT INTO Landen (land) VALUES ('Tanzania');
INSERT INTO Landen (land) VALUES ('Ukraine');
INSERT INTO Landen (land) VALUES ('Uganda');
INSERT INTO Landen (land) VALUES ('U.S. Minor Outlying Islands');
INSERT INTO Landen (land) VALUES ('United States');
INSERT INTO Landen (land) VALUES ('Uruguay');
INSERT INTO Landen (land) VALUES ('Uzbekistan');
INSERT INTO Landen (land) VALUES ('Vatican City');
INSERT INTO Landen (land) VALUES ('Saint Vincent and the Grenadines');
INSERT INTO Landen (land) VALUES ('Venezuela');
INSERT INTO Landen (land) VALUES ('British Virgin Islands');
INSERT INTO Landen (land) VALUES ('U.S. Virgin Islands');
INSERT INTO Landen (land) VALUES ('Vietnam');
INSERT INTO Landen (land) VALUES ('Vanuatu');
INSERT INTO Landen (land) VALUES ('Wallis and Futuna');
INSERT INTO Landen (land) VALUES ('Samoa');
INSERT INTO Landen (land) VALUES ('Kosovo');
INSERT INTO Landen (land) VALUES ('Yemen');
INSERT INTO Landen (land) VALUES ('Mayotte');
INSERT INTO Landen (land) VALUES ('South Africa');
INSERT INTO Landen (land) VALUES ('Zambia');
INSERT INTO Landen (land) VALUES ('Zimbabwe');
